/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as FountySecureAccessRouteImport } from './routes/founty-secure-access'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSurMesureRouteImport } from './routes/admin.sur-mesure'
import { Route as AdminLookbookRouteImport } from './routes/admin.lookbook'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminCatalogueRouteImport } from './routes/admin.catalogue'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const FountySecureAccessRoute = FountySecureAccessRouteImport.update({
  id: '/founty-secure-access',
  path: '/founty-secure-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurMesureRoute = AdminSurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLookbookRoute = AdminLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/founty-secure-access': typeof FountySecureAccessRoute
  '/profil': typeof ProfilRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/sur-mesure': typeof AdminSurMesureRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/founty-secure-access': typeof FountySecureAccessRoute
  '/profil': typeof ProfilRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/sur-mesure': typeof AdminSurMesureRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/founty-secure-access': typeof FountySecureAccessRoute
  '/profil': typeof ProfilRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/lookbook': typeof AdminLookbookRoute
  '/admin/sur-mesure': typeof AdminSurMesureRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/collections'
    | '/founty-secure-access'
    | '/profil'
    | '/admin/catalogue'
    | '/admin/commandes'
    | '/admin/lookbook'
    | '/admin/sur-mesure'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/collections'
    | '/founty-secure-access'
    | '/profil'
    | '/admin/catalogue'
    | '/admin/commandes'
    | '/admin/lookbook'
    | '/admin/sur-mesure'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/collections'
    | '/founty-secure-access'
    | '/profil'
    | '/admin/catalogue'
    | '/admin/commandes'
    | '/admin/lookbook'
    | '/admin/sur-mesure'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  FountySecureAccessRoute: typeof FountySecureAccessRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founty-secure-access': {
      id: '/founty-secure-access'
      path: '/founty-secure-access'
      fullPath: '/founty-secure-access'
      preLoaderRoute: typeof FountySecureAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sur-mesure': {
      id: '/admin/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/admin/sur-mesure'
      preLoaderRoute: typeof AdminSurMesureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lookbook': {
      id: '/admin/lookbook'
      path: '/lookbook'
      fullPath: '/admin/lookbook'
      preLoaderRoute: typeof AdminLookbookRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminLookbookRoute: typeof AdminLookbookRoute
  AdminSurMesureRoute: typeof AdminSurMesureRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminLookbookRoute: AdminLookbookRoute,
  AdminSurMesureRoute: AdminSurMesureRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  FountySecureAccessRoute: FountySecureAccessRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
